<template>
  <div class="ma-content-block lg:flex justify-between p-4">
    <!-- CRUD 组件 -->
    <ma-crud :options="crud" :columns="columns" ref="crudRef">
    </ma-crud>
  </div>
</template>

<script setup>
  import { ref, reactive, computed } from 'vue'
  import api from '../../api/news/banner'

  const crudRef = ref()


  const crud = reactive({
    api: api.getPageList,
    recycleApi: api.getRecyclePageList,
    showIndex: false,
    searchColNumber: 3,
    pageLayout: 'fixed',
    rowSelection: { showCheckedAll: true },
    operationColumn: true,
    operationColumnWidth: 160,
    add: { show: true, api: api.save, auth: ['/saicms/news/banner/save'] },
    edit: { show: true, api: api.update, auth: ['/saicms/news/banner/update'] },
    delete: { show: true, api: api.delete, auth: ['/saicms/news/banner/destroy'], realApi: api.realDestroy, realAuth: ['/saicms/news/banner/realDestroy'] },
    recovery: { show: true, api: api.recovery, auth: ['/saicms/news/banner/recovery']},
    formOption: { width: 800 },
  })

  const columns = reactive([
    {
      title: '编号',
      dataIndex: 'id',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: true, message: '编号必填' }],
    },
    {
      title: '类型',
      dataIndex: 'banner_type',
      width: 100,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      dict: { data: [{"label":"首页","value":1}], translation: true },
      formType: 'select',
      commonRules: [{ required: true, message: '类型必填' }],
    },
    {
      title: '标题',
      dataIndex: 'title',
      width: 300,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '标题必填' }],
    },
    {
      title: '图片地址',
      dataIndex: 'image',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'upload',
      type: 'image',
      returnType: 'url',
      multiple: false,
      commonRules: [{ required: false, message: '图片地址必填' }],
    },
    {
      title: '是否链接',
      dataIndex: 'is_href',
      width: 100,
      search: false,
      addDisplay: true, addDefaultValue: 1,
      editDisplay: true,
      hide: false,
      dict: { name: 'yes_or_no', props: { label: 'label', value: 'value' }, translation: true },
      formType: 'radio',
      commonRules: [{ required: false, message: '是否链接必填' }],
    },
    {
      title: '链接地址',
      dataIndex: 'url',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '链接地址必填' }],
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      search: true,
      addDisplay: true, addDefaultValue: 1,
      editDisplay: true,
      hide: false,
      dict: { name: 'data_status', props: { label: 'label', value: 'value' }, translation: true },
      formType: 'radio',
      commonRules: [{ required: false, message: '状态必填' }],
    },
    {
      title: '排序',
      dataIndex: 'sort',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'inputNumber',
      commonRules: [{ required: false, message: '排序必填' }],
    },
    {
      title: '描述',
      dataIndex: 'remark',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: true,
      formType: 'textarea',
      commonRules: [{ required: false, message: '描述必填' }],
    },
    {
      title: '创建者',
      dataIndex: 'created_by',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '创建者必填' }],
    },
    {
      title: '更新者',
      dataIndex: 'updated_by',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '更新者必填' }],
    },
    {
      title: '创建时间',
      dataIndex: 'create_time',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      searchFormType: 'range',
      showTime: true,
      formType: 'date',
      commonRules: [{ required: false, message: '创建时间必填' }],
    },
    {
      title: '修改时间',
      dataIndex: 'update_time',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      searchFormType: 'range',
      showTime: true,
      formType: 'date',
      commonRules: [{ required: false, message: '修改时间必填' }],
    },
  ])
</script>
